### ISSUE TITLE
Does not work for LG Devices

### ISSUE THREAD

**Issue by sudhirconscious** [leolin310148/ShortcutBadger#34] opened 2015-08-13 07:19 UTC
The badger does not seem to work on LG device. I tried checking with Nova & Apex launchers but still the badge count does not show up. Do i need to do anything else to make it work..?

**Comment by leolin310148** [comment] 2015-08-13 09:10
Hi, can you try the Sample App and tell me the launcher name display in the SampleApp ?

**Comment by sudhirconscious** [comment] 2015-08-13 09:57
Thanks for quick response.
Following are the launcher names for which badger is not working::
com.anddoes.launcher - apex launcher
and
com.teslacoilsw.launcher - nova launcher

**Comment by sudhirconscious** [comment] 2015-08-14 05:06
any reason its not working for these …?

**Comment by aila-cherim** [comment] 2015-08-14 06:12
Hi, also i had problems with Samsung devices. The app after including ShortcutBadger became unresponsive at startup.
I saw that the problem is in SamsungHomeBadger in executeBadge method. I modified the code from executeBadge method and now it works.
I will paste here the code that is working.

  ContentValues cv = new ContentValues();
        cv.put("package", mContext.getPackageName());
        // Name of your activity declared in the manifest as android.intent.action.MAIN.
        // Must be fully qualified name as shown below
        cv.put("class", getEntryActivityName());
        cv.put("badgecount", badgeCount); // integer count you want to display

        // Execute insert
        mContext.getContentResolver().update(Uri.parse("content://com.sec.badge/apps"), cv, "package=?", new String[]{mContext.getPackageName()});

I think something is happening on ui thread.
Also on Samsung S4 is not really blocking the ui but on Samsung devices that are low this is happening.

I cannot attach some logs from Samsung S4 but i will paste here some of them.
08-14 09:06:23.952    8118-8118/? D/BadgeProvider﹕ onCreate
08-14 09:06:23.952    8118-8118/? D/BadgeProvider﹕ DatabaseHelper
08-14 09:06:23.982    8118-8137/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:23.982    8118-8137/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:23.982    8118-8137/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:23.982    8118-8137/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:23.982    8118-8137/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:23.992    8118-8135/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:23.992    8118-8135/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:23.992    8118-8135/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:23.992    8118-8135/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:23.992    8118-8135/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.002    8118-8137/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.002    8118-8137/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.002    8118-8137/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.002    8118-8137/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.002    8118-8137/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.002    8118-8133/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.002    8118-8133/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.002    8118-8133/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.002    8118-8133/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.002    8118-8133/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.012    8118-8137/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.012    8118-8137/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.012    8118-8137/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.012    8118-8137/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.012    8118-8137/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.012    8118-8139/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.012    8118-8139/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.012    8118-8139/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.012    8118-8139/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.012    8118-8139/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.022    8118-8133/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.022    8118-8133/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.022    8118-8133/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.022    8118-8133/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.022    8118-8133/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.022    8118-8135/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.022    8118-8135/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.022    8118-8135/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.022    8118-8135/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.022    8118-8135/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.032    8118-8133/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.032    8118-8133/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.032    8118-8133/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.032    8118-8133/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.032    8118-8133/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.042    8118-8135/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.042    8118-8135/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.042    8118-8135/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.042    8118-8135/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.042    8118-8135/? D/BadgeProvider﹕ update, [UpdateCount] : 1
08-14 09:06:24.042    8118-8139/? D/BadgeProvider﹕ sendNotify entered. [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.042    8118-8139/? D/BadgeProvider﹕ sendNotify, [notify] : true
08-14 09:06:24.052    8118-8139/? D/BadgeProvider﹕ update, [uri] : content://com.sec.badge/apps?notify=true
08-14 09:06:24.052    8118-8139/? D/BadgeProvider﹕ update, [BadgeCount] : badgecount=0
08-14 09:06:24.052    8118-8139/? D/BadgeProvider﹕ update, [UpdateCount] : 1

**Comment by leolin310148** [comment] 2015-08-14 06:14
@aila-cherim 
The problem in Samsung has been resolved in 1.1.3

**Comment by leolin310148** [comment] 2015-08-14 06:16
@sudhirconscious 
apex only works with Pro version, and Nova launcher should work with teslaunread.

**Closed** 2015-11-05 11:12 UTC
