### ISSUE TITLE
Not working in Motorola devices

### ISSUE THREAD

**Issue by DheerajLPTPL** [leolin310148/ShortcutBadger#143] opened 2016-11-14 08:13 UTC
almost all device it is working but in Motorola it do'nt work.

**Comment by rostopira** [comment] 2016-12-21 09:54
I was using motorola's for few years, their default launcher doesn't have badges, so it can't work

**Comment by rostopira** [comment] 2016-12-21 10:01
Exact duplicate of #123

**Closed** 2017-02-04 06:48 UTC
